In [31]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split,GridSearchCV,cross_val_score,cross_val_predict

In [2]:
df = pd.read_csv("Advertising_data.csv.txt")

In [3]:
df.head()

User ID  Gender   Age  EstimatedSalary  Purchased
0  15624510    Male  19.0          19000.0          0
1  15810944    Male  35.0          20000.0          0
2  15668575  Female  26.0          43000.0          0
3  15603246  Female  27.0          57000.0          0
4  15804002    Male  19.0          76000.0          0

In [4]:
X = df[['Age','EstimatedSalary']]
y = df['Purchased']


In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [6]:
log = SVC()
mainLog = SVC()
log.fit(X_train,y_train)
predict = log.predict(X_test)
accuracy_score(predict,y_test)

0.946969696969697

In [7]:
# grid_search
parameters = [{'C':[1,10,100,1000],'kernel':['linear']},
              {'C':[1,10,100,1000],'kernel':['rbf'],'gamma':[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]}
              ]
grid_search = GridSearchCV(estimator=mainLog,param_grid=parameters,n_jobs=-1,scoring="accuracy")
grid_search.fit(X_train,y_train)

C:\Users\musta\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto_deprecated', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='warn', n_jobs=-1,
             param_grid=[{'C': [1, 10, 100, 1000], 'kernel': ['linear']},
                         {'C': [1, 10, 100, 1000],
                          'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8,
                                    0.9],
                          'kernel': ['rbf']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy', verbose=0)

In [8]:
grid_search.best_params_

{'C': 1, 'gamma': 0.5, 'kernel': 'rbf'}

In [9]:
pd.DataFrame(grid_search.cv_results_).sort_values(by=['mean_test_score'],ascending=False)

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
15       0.004730      0.001031         0.001331        0.001883      10   
8        0.004001      0.000008         0.004402        0.000574       1   
9        0.005002      0.000765         0.000000        0.000000       1   
10       0.003977      0.001470         0.000000        0.000000       1   
11       0.004861      0.002762         0.001331        0.001882       1   
12       0.003067      0.002225         0.001344        0.001900       1   
31       0.011559      0.004977         0.001338        0.001893    1000   
26       0.004784      0.000555         0.003158        0.002270     100   
25       0.005727      0.001686         0.001333        0.001885     100   
24       0.004182      0.001634         0.000000        0.000000     100   
16       0.004073      0.001728         0.001339        0.001894      10   
20       0.002653      0.001876         0.001350        0.001909      10   
32       0.017241      0.002221         0.001332        0.001883    1000   
23       0.005414      0.001003         0.002775        0.001964     100   
19       0.002672      0.001889         0.001389        0.001965      10   
17       0.001337      0.001891         0.001410        0.001995      10   
7        0.004524      0.000446         0.001396        0.001974       1   
14       0.003428      0.002588         0.001332        0.001884      10   
18       0.002062      0.002249         0.001333        0.001885      10   
33       0.034538      0.025720         0.002664        0.001884    1000   
21       0.002454      0.002796         0.002673        0.001890      10   
22       0.004398      0.000570         0.001663        0.001696     100   
28       0.006089      0.001615         0.002679        0.001894     100   
30       0.006539      0.001957         0.000000        0.000000     100   
5        0.003112      0.002259         0.003226        0.001598       1   
6        0.003678      0.001975         0.001769        0.001842       1   
36       0.015638      0.006775         0.000000        0.000000    1000   
13       0.002995      0.001412         0.002769        0.001960      10   
35       0.033806      0.022983         0.001432        0.002025    1000   
27       0.004707      0.000940         0.003161        0.002272     100   
29       0.004430      0.000618         0.000000        0.000000     100   
34       0.016271      0.008958         0.001331        0.001883    1000   
4        0.003957      0.000065         0.001665        0.001697       1   
37       0.019944      0.009983         0.001332        0.001884    1000   
38       0.021544      0.012702         0.001338        0.001892    1000   
39       0.016603      0.006594         0.000666        0.000942    1000   
1        0.006512      0.001044         0.001022        0.001445      10   
3        0.136718      0.020018         0.001332        0.001883    1000   
2        0.021353      0.001771         0.000971        0.000782     100   
0        0.004965      0.003247         0.002831        0.002118       1   

   param_kernel param_gamma                                      params  \
15          rbf         0.3    {'C': 10, 'gamma': 0.3, 'kernel': 'rbf'}   
8           rbf         0.5     {'C': 1, 'gamma': 0.5, 'kernel': 'rbf'}   
9           rbf         0.6     {'C': 1, 'gamma': 0.6, 'kernel': 'rbf'}   
10          rbf         0.7     {'C': 1, 'gamma': 0.7, 'kernel': 'rbf'}   
11          rbf         0.8     {'C': 1, 'gamma': 0.8, 'kernel': 'rbf'}   
12          rbf         0.9     {'C': 1, 'gamma': 0.9, 'kernel': 'rbf'}   
31          rbf         0.1  {'C': 1000, 'gamma': 0.1, 'kernel': 'rbf'}   
26          rbf         0.5   {'C': 100, 'gamma': 0.5, 'kernel': 'rbf'}   
25          rbf         0.4   {'C': 100, 'gamma': 0.4, 'kernel': 'rbf'}   
24          rbf         0.3   {'C': 100, 'gamma': 0.3, 'kernel': 'rbf'}   
16          rbf         0.4    {'C': 10, 'gamma': 0.4, 'kernel

In [10]:
log = SVC(C=1,gamma=0.5,kernel='rbf')
log.fit(X_train,y_train)

predict = log.predict(X_test)
accuracy_score(predict,y_test)

0.946969696969697

In [11]:
log = LogisticRegression()
log.fit(X_train,y_train)
predict = log.predict(X_test)
accuracy_score(predict,y_test)

C:\Users\musta\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.8333333333333334

In [12]:
log = RandomForestClassifier()
log.fit(X_train,y_train)
predict = log.predict(X_test)
accuracy_score(predict,y_test)

C:\Users\musta\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


0.8939393939393939

In [13]:
grid_search.best_params_
grid_search.best_estimator_

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.5, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [14]:
log = RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=10, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=25,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)
log.fit(X_train,y_train)
predict = log.predict(X_test)
accuracy_score(predict,y_test)

0.9015151515151515

In [15]:
n_estimators=[500, 800, 1500, 2500, 5000]
max_features = ['auto', 'sqrt', 'log2']
max_depth = [10, 20, 30, 401,50]
minsamples_split = [2, 5, 10, 15, 20]
minsamplesleaf = [1, 2, 51,10,15] 

grid_param = {
    'n_estimators':n_estimators,
    'max_features':max_features,
    'max_depth':max_depth,
    'min_samples_split':minsamples_split,
    'min_samples_leaf':minsamplesleaf
}

In [16]:
# grid_search = GridSearchCV(log,cv=15,param_grid=grid_param,n_jobs=-1)
# grid_search.fit(X_train,y_train)

In [21]:
model_params = {
    'svm': {
        'model': SVC(gamma='auto'),
        'params' : {
            'C': [1,10,20],
            'kernel': ['rbf','linear']
        }  
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params' : {
            'n_estimators': [1,5,10]
        }
    },
    'decision_tree': {
        'model': DecisionTreeClassifier(),
        'params': {
            'criterion': ['gini','entropy'],
            
        }
    }     
}

In [25]:
from sklearn.model_selection import GridSearchCV
import pandas as pd
scores = []

for model_name, mp in model_params.items():
    clf =  GridSearchCV(mp['model'], mp['params'], cv=15, return_train_score=False)
    clf.fit(X_train,y_train)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })
    
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df

C:\Users\musta\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)
C:\Users\musta\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)
C:\Users\musta\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


model  best_score                best_params
0            svm    0.891791  {'C': 1, 'kernel': 'rbf'}
1  random_forest    0.876866       {'n_estimators': 10}
2  decision_tree    0.850746      {'criterion': 'gini'}

In [27]:
log = RandomForestClassifier(n_estimators=10)
log.fit(X_train,y_train)
accuracy_score(log.predict(X_test),y_test)

0.9015151515151515

In [29]:
log = DecisionTreeClassifier(criterion='gini')
log.fit(X_train,y_train)
accuracy_score(log.predict(X_test),y_test)

0.8636363636363636

In [32]:
cross_val_score(DecisionTreeClassifier(criterion='gini'),X,y)

C:\Users\musta\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


array([0.82835821, 0.85074627, 0.76515152])

In [42]:
cross_val_score(DecisionTreeClassifier(criterion='gini'),X,y)

C:\Users\musta\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


array([0.82835821, 0.85074627, 0.77272727])

In [43]:
cross_val_score(RandomForestClassifier(n_estimators=10),X,y)

C:\Users\musta\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


array([0.82089552, 0.89552239, 0.78787879])